var shayan = document.getElementById("container")
shayan.setAttribute("class", "Container")
var Create = document.createElement("img")
Create.setAttribute("src", "http://pluspng.com/img-png/headphones-hd-png-headphones-png-image-1005.png")
shayan.appendChild(Create)
Create.setAttribute("class", "roll-in-top")
var text = document.createElement("p")
var textP = document.createTextNode("Wireless bluetooth headset")
text.setAttribute("class", ("Head"))
text.appendChild(textP)
shayan.appendChild(text)
var Description = document.createElement("p")
var DescriptionText = document.createTextNode("Shipped in 3-4 days")
Description.appendChild(DescriptionText)
shayan.appendChild(Description)
Description.setAttribute("class", "Description")
var Dollar = document.createElement("p")
var DollarText = document.createTextNode("35 $")
Dollar.appendChild(DollarText)
shayan.appendChild(Dollar)
Dollar.setAttribute("class", "Dollar")
BtnCart = document.createElement("button")
BtnCart1 = document.createTextNode("Add to Cart")
BtnCart.appendChild(BtnCart1)
shayan.appendChild(BtnCart)
BtnCart.setAttribute("class","slide-in-left")

BtnBuy = document.createElement("button")
BtnBuy1 = document.createTextNode("Buy")
BtnBuy.appendChild(BtnBuy1)
shayan.appendChild(BtnBuy)
BtnBuy.setAttribute("class", "slide-in-right")